FROM rabbitmq:3.13.2-management-alpine AS install

# COPY ../secrets/config.json /etc/rabbitmq/definitions.json

ENV RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
ENV RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}